#!/usr/bin/env python3
"""Render a project.cfx as a readable Markdown pipeline map. Reading never touches SQX state."""

import argparse
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import project_map
from core.cfx import resolve


def build(project: str) -> str:
    """The whole pipeline map for one project.

    Args:
        project: Project name under the master's user/projects, or a path to a .cfx.

    Returns:
        Markdown: header, databanks, TL;DR, databank flow, task order, per-task detail.
    """
    path = resolve(project)
    with zipfile.ZipFile(path) as z:
        cfg = ElementTree.fromstring(z.read("config.xml"))
        tasks = cfg.findall("Tasks/Task")
        task_xml = {i: ElementTree.fromstring(z.read(t.get("taskXMLFile")))
                    for i, t in enumerate(tasks, 1)}

    flow = project_map.databank_flow(cfg, task_xml)
    lines = [f"# {cfg.get('name')} — pipeline map", "",
             f"Generated by `1_sqx/inspect/dump_project.py` from `{path}`.",
             f"Project declares `version=\"{cfg.get('version')}\"`.", "",
             "> **Read-only artefact.** Regenerate rather than hand-editing. Never edit a",
             "> `project.cfx` on disk while SQX holds the project: SQX rewrites the whole",
             "> file on save and exit, and the change is silently lost.", ""]
    lines += project_map.databank_table(cfg)
    lines += project_map.tldr(cfg, task_xml, flow)
    lines += project_map.flow_table(flow, cfg)
    lines += project_map.task_order(cfg, task_xml)
    lines += ["## Tasks in detail", ""]
    for i, t in enumerate(tasks, 1):
        lines += project_map.task_detail(i, t, task_xml[i])
    return "\n".join(lines)


def main() -> None:
    """Write the map to a file, or print it."""
    ap = argparse.ArgumentParser()
    ap.add_argument("project", help="project name on the master, or a path to a .cfx")
    ap.add_argument("-o", "--out", type=Path)
    a = ap.parse_args()

    doc = build(a.project)
    if a.out:
        a.out.write_text(doc, encoding="utf-8")
        print(f"wrote {a.out} ({len(doc)} bytes)", file=sys.stderr)
    else:
        print(doc)


if __name__ == "__main__":
    main()
