"""Per-asset trading-cost overrides. Run as a module for the preflight every project needs."""

import sys
from pathlib import Path

import yaml

from core.paths import ASSETS

REQUIRED = ("spread", "commission")


def load(symbol: str) -> dict:
    """Read one asset's override file.

    Args:
        symbol: Asset name as the file is called, e.g. "NAS100".

    Returns:
        The parsed YAML. Raises FileNotFoundError when the asset has no file, which
        is the intended outcome: nothing may be authored for an unknown asset.
    """
    return yaml.safe_load((ASSETS / f"{symbol}.yaml").read_text(encoding="utf-8"))


def special_notes() -> list[Path]:
    """Cross-asset special cases that apply to every project.

    Returns:
        Paths of every file in assets/special/, sorted.
    """
    return sorted((ASSETS / "special").glob("*.md"))


def pending(data: dict) -> list[str]:
    """Fields whose real value the owner has not decided yet.

    Args:
        data: One asset's parsed override file.

    Returns:
        Names of required fields still carrying a null `use` value.
    """
    return [k for k in REQUIRED if data.get(k, {}).get("use") is None]


def report(symbol: str) -> str:
    """The text a session must read out before authoring anything for this asset.

    Args:
        symbol: Asset name.

    Returns:
        Markdown listing every override, why it differs from SQX, and what is still undecided.
    """
    data = load(symbol)
    lines = [f"# {symbol} — overrides to apply", "",
             f"SQX symbol: {data['sqx_symbol']}   verified: {data['verified']}", ""]
    for field, spec in data.items():
        if not isinstance(spec, dict) or "use" not in spec:
            continue
        use = spec["use"] if spec["use"] is not None else "UNDECIDED"
        lines.append(f"- **{field}**: use `{use}` {spec.get('unit', '')}"
                     f" (SQX default `{spec.get('sqx_default')}`) — {spec.get('why', '')}")
    for note in data.get("notes", []):
        lines.append(f"- note: {note}")
    for f in special_notes():
        lines.append(f"- also read: assets/special/{f.name}")
    return "\n".join(lines)


def write_index() -> int:
    """Regenerate assets/INDEX.md, one line per asset.

    Returns:
        How many assets were listed. The index exists so a session can see what is decided
        without opening seventeen files.
    """
    lines = ["# assets — index", "",
             "Generated by `python3 -m core.assets --index`. Read `RULES.md` first.", "",
             "| asset | SQX symbol | spread (SQX → use) | commission (SQX → use) | decided |",
             "|---|---|---|---|---|"]
    files = sorted(ASSETS.glob("*.yaml"))
    for f in files:
        d = yaml.safe_load(f.read_text(encoding="utf-8"))
        s, c = d["spread"], d["commission"]
        done = "—" if pending(d) else "✅"
        lines.append(f"| `{d['symbol']}` | `{d['sqx_symbol']}` | {s['sqx_default']} → "
                     f"{s['use'] if s['use'] is not None else '?'} | {c['sqx_default']} → "
                     f"{c['use'] if c['use'] is not None else '?'} | {done} |")
    (ASSETS / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(files)


def main() -> None:
    """Print one asset's overrides; exit non-zero if the asset is unknown or undecided."""
    if sys.argv[1] == "--index":
        print(f"indexed {write_index()} assets")
        return
    symbol = sys.argv[1]
    print(report(symbol))
    missing = pending(load(symbol))
    if missing:
        print(f"\nBLOCKED: {', '.join(missing)} still have no agreed value. Ask the owner.")
        sys.exit(2)


if __name__ == "__main__":
    main()
