"""The data root's secondary trees: template library, pipeline, permutations, logs, backups, caches.

Split out of core/paths.py, which keeps the installs and the primary exports."""

from pathlib import Path

from core.paths import DATA


def template_dir(name: str) -> Path:
    """Folder of one strategy template in the library.

    Args:
        name: Template name in camelCase, underscores separating roles only, e.g.
            "keltnerCrossClose_atrTrail".

    Returns:
        Path under the data root. Self-contained — the .sqx, its brief and the blocks and
        groups it references — so it installs on any SQX unchanged. A template carries no
        symbol and no timeframe: those belong to a run.
    """
    return DATA / "templates" / "library" / name


def template_registry() -> Path:
    """The CSV of every template in the library, one row each.

    Returns:
        Path under the data root. CSV and not parquet because a human reads it; written by
        code, never hand-edited.
    """
    return DATA / "templates" / "registry.csv"


def template_runs() -> Path:
    """The CSV of every (template, symbol, timeframe) that has been tried.

    Returns:
        Path under the data root. Separate from the registry because one template is tried
        on many markets: "have I run this on NASDAQ H1" is a row here, not a second copy.
    """
    return DATA / "templates" / "runs.csv"


def vocabulary_snapshot(install: str, day: str) -> Path:
    """Where one install's block-and-group inventory is kept.

    Args:
        install: Folder name of the install, e.g. "SQX_w1".
        day: Snapshot date as YYYY-MM-DD.

    Returns:
        Path under the data root. Dated and kept, not replaced: the point is comparing
        installs and dates, which a single current file cannot answer.
    """
    return DATA / "templates" / "vocabulary" / f"{install}-{day}.json"


def pipeline_dir(project: str, strategy_slug: str) -> Path:
    """One mother strategy's pipeline ledger and stage outputs.

    Args:
        project: Project name on the master.
        strategy_slug: The strategy name as `pipeline.ledger.state.safe` spells it.

    Returns:
        Path under the data root. The ledger outlives the data `pipeline.cleanup` sweeps.
    """
    return DATA / "pipeline" / project / strategy_slug


def variants_dir(project: str, strategy: str) -> Path:
    """One strategy's fabricated permutations and their manifest; rebuilding replaces it.

    Args:
        project: Project name on the master.
        strategy: Strategy name as SQX writes it.

    Returns:
        Path under the data root.
    """
    return DATA / "strategyPermutations" / project / strategy.replace(" ", "_")


def log_archive(install_name: str) -> Path:
    """One install's SQX logs, gzipped before SQX prunes them; `projects/<P>/` condensed.

    Args:
        install_name: Folder name of the install, e.g. "SQX" or "SQX_w1".

    Returns:
        Path under the data root, mirroring `<install>/user/log`.
    """
    return DATA / "logs" / install_name


def data_update_backups() -> Path:
    """Where `sqx.data.update` records what it saw before touching the master's data.

    Returns:
        Path under the data root, one JSON per run.
    """
    return DATA / "backups" / "data-update"


def projects_backup(name: str) -> Path:
    """A frozen copy: a donor `project.cfx`, mother strategies, install configs.

    Args:
        name: Folder name, e.g. "XAUUSD_base_2026-09-21".

    Returns:
        Path under the data root. SQX rewrites a live `project.cfx` on save and exit, so
        the copy here is the fixed point new projects are cloned from.
    """
    return DATA / "projectsBackup" / name


def cache_dir(name: str) -> Path:
    """A disposable cache, regenerated by whoever reads it.

    Args:
        name: Which cache, e.g. "montecarlo" or "crossmarket".

    Returns:
        Path under the data root. Deleting it costs a recomputation and nothing else.
    """
    return DATA / "cache" / name
