"""Read a .sqx strategy without SQX. It is a ZIP; everything useful is in its inner XML."""

import hashlib
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree

INNER = "strategy_Portfolio.xml"
# 🔬 2026-09-23: a retest rewrites `makeExternal` on every <variable> and changes nothing
# else. Hashing the raw XML therefore gives a strategy one identity in the build databank
# and another in the retest one -- 0 of 115 matched. Stripping it: 115 of 115.
# 🔬 2026-09-27: after the MC Retest SQX also drops `autoGenerated="true"` from every
# <variable>, in the databank it read -- the identity changed in place and /curate refused a
# verdict written an hour earlier. Stripped too (owner, 2026-09-27).
COSMETIC = re.compile(r'\s*(?:makeExternal|autoGenerated)="[^"]*"')
BLOCK_KEY = re.compile(r'<Item[^>]*\bkey="([^"]+)"')
RESULTS_RE = re.compile(r"Results/[^:]*:\s*([A-Z0-9]+)_([^/]*)/")
# The five paramType strings the corrected "Param Count" counts (knowhow/columns/param-count.md,
# fixed 2026-09-06): Period, Constant, EntryLevel, OtherParam, ExitUsed. Excludes MagicNumber,
# the four signal variables and Shift — none carries a paramType SQX ever sets.
COUNTED_PARAM_TYPES = frozenset({"ParamTypePeriod", "ParamTypeConstant", "ParamTypeEntryLevel",
                                 "ParamTypeOtherParam", "ParamTypeExitUsed"})


def identity(path: Path) -> str:
    """Stable identity of a strategy.

    Args:
        path: A .sqx file.

    Returns:
        SHA-256 of the inner strategy_Portfolio.xml with SQX's own bookkeeping stripped.
        Never hash the .sqx itself: the ZIP embeds timestamps, so identical strategies get
        different file hashes. And never hash the XML raw either — a retest flips
        `makeExternal` on every variable, so the same strategy carries one hash in the
        build databank and a different one in the retest databank, which is exactly the
        join those two databanks have to be paired on.
    """
    return _hashed(rules(path))


def _hashed(text: str) -> str:
    """identity() of a strategy definition already read out of its archive."""
    return hashlib.sha256(COSMETIC.sub("", text).encode("utf-8")).hexdigest()


def describe(path: Path) -> tuple[str, str, str]:
    """identity() and symbol() together, from one opening of the archive.

    Args:
        path: A .sqx file.

    Returns:
        (identity, symbol, feed). Reading a ZIP's directory is most of what either costs on
        its own -- a result-laden .sqx carries some 250 entries -- so a scan that wants both
        opens it once. 🔬 2026-09-25, `index_sqx` over 19,328 files was paying it twice.
    """
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        text = z.read(next(n for n in names if n.endswith(INNER))).decode("utf-8", "replace")
    found = next((m for m in map(RESULTS_RE.search, names) if m), None)
    return _hashed(text), *((found.group(1), found.group(2)) if found else ("", ""))


def rules(path: Path) -> str:
    """The strategy's definition, as text.

    Args:
        path: A .sqx file.

    Returns:
        The inner strategy_Portfolio.xml decoded. Everything that says what the strategy
        DOES is in here; the rest of the archive is results.
    """
    with zipfile.ZipFile(path) as z:
        inner = next(n for n in z.namelist() if n.endswith(INNER))
        return z.read(inner).decode("utf-8", "replace")


def structure(path: Path) -> str:
    """Identity of a strategy's LOGIC, ignoring what its parameters are set to.

    Args:
        path: A .sqx file.

    Returns:
        SHA-256 over the ordered block keys of the strategy. Two strategies share it when
        they are the same rules at different settings — a moving average of 14 and one of
        90 are one idea, not two. On the 115 of a sample build that is 24 distinct shapes,
        two of them holding 32 strategies each: the population is a sixth as diverse as
        its count suggests.
    """
    return hashlib.sha256("|".join(BLOCK_KEY.findall(rules(path))).encode()).hexdigest()


def symbol(path: Path) -> tuple[str, str]:
    """Symbol and data feed a strategy was tested on.

    Args:
        path: A .sqx file.

    Returns:
        (symbol, feed), e.g. ("XAUUSD", "DukasM1_Infinox_LOM_M30"), read from the ZIP
        entry names. Far cheaper than opening the multi-MB settings.xml.
    """
    with zipfile.ZipFile(path) as z:
        for name in z.namelist():
            m = RESULTS_RE.search(name)
            if m:
                return m.group(1), m.group(2)
    return "", ""


def xml(path: Path) -> ElementTree.Element:
    """Parsed strategy definition.

    Args:
        path: A .sqx file.

    Returns:
        Root element of strategy_Portfolio.xml — the rules, parameters and orders.
    """
    with zipfile.ZipFile(path) as z:
        inner = next(n for n in z.namelist() if n.endswith(INNER))
        return ElementTree.fromstring(z.read(inner))


def parameters(path: Path) -> dict[str, str]:
    """Every named parameter of a strategy and its value.

    Args:
        path: A .sqx file.

    Returns:
        Parameter name to value as stored, e.g. {"#Size#": "0.1"}. The value is the
        element's text, not an attribute.
    """
    return {p.get("key"): (p.text or "").strip()
            for p in xml(path).iter("Param") if p.get("key")}


def param_count(path: Path) -> int:
    """The "Param Count" column, recomputed from `<Variables>` — never SQX's stored value.

    Args:
        path: A .sqx file.

    Returns:
        How many `<variable>` elements carry a `<paramType>` in `COUNTED_PARAM_TYPES`. SQX
        stores this count in the result it computes it under and never recomputes it
        (`compute()` runs once), so every strategy built before 2026-09-06 carries the old,
        inflated value forever (`knowhow/columns/param-count.md`). This mirrors the fixed
        Java logic directly off the strategy definition, so it is right for every strategy
        regardless of when it was built or last retested.
    """
    return sum(1 for v in xml(path).iter("variable")
              if (v.findtext("paramType") or "") in COUNTED_PARAM_TYPES)


def sqx_filter(path: Path) -> str | None:
    """SQX's own pass or fail note on a strategy, as its last filtering task left it.

    Args:
        path: A .sqx file.

    Returns:
        The text of `<FiltersResultFailedReason>` in settings.xml — "Passed", or the reason,
        e.g. "Cross Check filter in 'Walk-Forward Matrix': Robustness score didn't pass." —
        and None when no task ever filtered it. 🔬 2026-09-26: with DeleteFailedStrategies
        false a strategy that fails the WFM area rule stays in the databank carrying this.
    """
    with zipfile.ZipFile(path) as z:
        found = re.search(r"<FiltersResultFailedReason[^>]*>([^<]*)<",
                          z.read("settings.xml").decode("utf-8", "replace"))
    return found.group(1).strip() if found else None
