"""Write the conclusions of one IS/OOS study as summary.md. Pure text: it computes nothing."""


def table(rows: list[dict], spec: list[tuple[str, str, str]]) -> str:
    """Render rows as a markdown table.

    Args:
        rows: One dict per line.
        spec: One (key, header, format spec) per column; an empty format spec prints the
            value unchanged.

    Returns:
        The table including its header and alignment rules.
    """
    head = "| " + " | ".join(h for _, h, _ in spec) + " |"
    rule = "|" + "|".join(" --- " if f == "" else " ---: " for _, _, f in spec) + "|"
    body = ["| " + " | ".join(str(r[k]) if f == "" else format(r[k], f)
                              for k, _, f in spec) + " |" for r in rows]
    return "\n".join([head, rule] + body)


def preamble(source: dict, n: int, r_crit: float, tested: int) -> list[str]:
    """The heading and the paragraph explaining what threshold the tables use.

    Args:
        source: Manifest fields plus the report date.
        n: Strategies in the export.
        r_crit: Correlation a single test must clear at the ordinary 5% level.
        tested: In-sample metrics tested against each outcome.

    Returns:
        Markdown lines.
    """
    return [
        f"# {source['project']} / {source['databank']} — in-sample against out-of-sample",
        "",
        f"{n:,} strategies · view \"{source['view']}\" · exported {source['exported']} · "
        f"report {source['reported']} · code {source['code_version']}",
        "",
        "These strategies were generated by search and none of them was selected on its",
        "out-of-sample result, so what follows is the unconditional relationship between an",
        "in-sample metric and what happened next. Read it as evidence about which metrics",
        "carry information, not as a ranking of strategies.",
        "",
        "## What counts as a discovery",
        "",
        f"At n={n:,} a single correlation clears the ordinary two-tailed 5% level at "
        f"|r| > {r_crit:.3f},",
        f"which is far too low to mean anything on its own. {tested} in-sample metrics are tested",
        "against each outcome, so the threshold used below is Benjamini-Hochberg at a 5% false",
        "discovery rate across each family. Metrics that survive it are marked ✓.",
        "",
        "Spearman (ρ) leads every table: these metrics are heavy-tailed and one blow-up",
        "strategy moves Pearson (r) a long way. Where the two disagree, suspect outliers.",
    ]


def findings(ranked: dict[str, list[dict]], found: dict[str, set[str]]) -> list[str]:
    """The plain-language conclusion per outcome.

    Args:
        ranked: Predictor rows per target, strongest first.
        found: Metric names surviving Benjamini-Hochberg, per target.

    Returns:
        Markdown lines.
    """
    lines = ["## Findings", ""]
    for target, rows in ranked.items():
        survivors = [r for r in rows if r["metric"] in found[target]]
        lines.append(f"**{target}** — {len(survivors)} of {len(rows)} in-sample metrics survive.")
        if survivors:
            best = ", ".join(f"{r['metric']} (ρ {r['spearman']:+.3f})" for r in survivors[:3])
            lines.append(f"Strongest: {best}.")
        lines.append("")
    lines += [
        "A ρ around 0.2 is a real relationship but a weak one: it shifts the odds, it does not",
        "decide the outcome. Whether shifting them that far is worth the strategies a filter",
        "throws away is a different question, and `tasks/TODO.md` describes the module that",
        "answers it.",
    ]
    return lines


def render(source: dict, n: int, r_crit: float, persist: list[dict],
           ranked: dict[str, list[dict]], found: dict[str, set[str]]) -> str:
    """Assemble the whole summary.

    Args:
        source: Manifest fields plus the report date.
        n: Strategies in the export.
        r_crit: Correlation a single test must clear at the ordinary 5% level.
        persist: Persistence rows, strongest first.
        ranked: Predictor rows per target, strongest first.
        found: Metric names surviving Benjamini-Hochberg, per target.

    Returns:
        The complete markdown document.
    """
    lines = preamble(source, n, r_crit, len(next(iter(ranked.values()))))
    lines += [
        "",
        "## Does a metric keep its own value out of sample?",
        "",
        "Same metric, in-sample against out-of-sample. `OOS/IS` below 1 is decay.",
        "",
        table(persist, [("metric", "metric", ""), ("is_mean", "IS mean", ",.2f"),
                        ("oos_mean", "OOS mean", ",.2f"), ("decay", "OOS/IS", ".2f"),
                        ("spearman", "ρ", "+.3f"), ("pearson", "r", "+.3f"),
                        ("p", "p", ".2e")]),
    ]
    for target, rows in ranked.items():
        marked = [dict(r, mark="✓" if r["metric"] in found[target] else "") for r in rows]
        lines += [
            "",
            f"## Which in-sample metric predicts {target}?",
            "",
            table(marked, [("metric", "IS metric", ""), ("spearman", "ρ", "+.3f"),
                           ("pearson", "r", "+.3f"), ("p", "p", ".2e"),
                           ("mark", "BH", "")]),
        ]
    return "\n".join(lines + [""] + findings(ranked, found)) + "\n"
