#!/usr/bin/env python3
"""Step 4's feed-quality scan: every feed of the bar library under its frozen K and session.

Writes, per feed, `feedQuality/<feed>/` under the data root: `events.parquet` (one row per
anomaly, what step 8 attributes against), `summary.json` (what the preflight reads) and the
report as `feedQuality.json/.html/.md`; plus the library's calendar and one row per feed in
AlgoData/INDEX.md. Describes feeds only: no strategy is read.
"""

import argparse
import json
from datetime import date

import numpy as np
import pandas as pd

from core import fanout
from core.paths import DATA, feed_quality_dir
from core.study import output
from core.study.result import progress
from engines.market.feed import session
from studies.data.feedQuality import calendar, detect, feed, inputs, summary

CFG: dict = {}
RUNS: list = []
BEGIN, END = "<!-- feedQuality:begin -->", "<!-- feedQuality:end -->"


def facts(name: str, b: dict, got: dict, ev: pd.DataFrame, tick: float) -> dict:
    """The flat numbers of one feed: what the preflight, the report and INDEX.md print."""
    yearly = summary.counts(ev, "Y")
    last_full = int(b["t"][-1].year) - 1
    since = yearly[(yearly.index >= CFG["stable"]["base_year"]) & (yearly.index <= last_full)]
    stable, grade = summary.stability(yearly, CFG)
    _, medians = summary.k_star(detect.yearly_counts(b, got, CFG["k"]["candidates"]), CFG)
    return {"feed": name, "K": CFG["K"][name], "tick": tick, "session": CFG["sessions"][name],
            "stable_from": stable, "grade": {str(y): g for y, g in grade.items()},
            "marked_per_year": float(since["marcadas"].median()),
            "per_year_median": {c: float(since[c].median()) for c in since.columns},
            "residual_gaps_per_year": summary.residual_gaps(yearly, CFG, last_full),
            "episodes": summary.episodes(summary.counts(ev, "M"), CFG).to_dict("records"),
            "quiet_medians": medians, "scanned_on": date.today().isoformat(),
            "bars_to": str(b["t"][-1])}


def one(name: str) -> dict:
    """Detect, classify, summarise and write one feed."""
    b = inputs.bars(name)
    tick = inputs.tick(b, CFG["session"]["years"])
    got = detect.measure(b, tick, CFG)
    ev = detect.events(b, got, CFG["K"][name], inputs.week_mask(CFG, name), CFG)
    holes = (ev["kind"] == "hueco") & (ev["cls"] == calendar.OWN)
    ev.loc[holes, "cls"] = calendar.classify(ev[holes], RUNS[0])
    out = feed_quality_dir(name)
    out.mkdir(parents=True, exist_ok=True)
    ev.to_parquet(out / "events.parquet")
    got_facts = facts(name, b, got, ev, tick)
    (out / "summary.json").write_text(json.dumps(got_facts, indent=1, ensure_ascii=False))
    output.population(out, "feedQuality", feed.run(name, ev, got_facts, CFG),
                      f"Calidad del feed — {name}")
    return got_facts


def index_rows(found: list[dict]) -> str:
    """The block INDEX.md carries between its two markers."""
    lines = [BEGIN, "## Feed quality", "",
             "Regenerated by `python3 -m studies.data.feedQuality.scan`: medians per full year "
             "since 2013 under each feed's frozen K and session (`ledger/thresholds.yaml`).", "",
             "| feed | K | estable desde | marcadas/año | pico-y-vuelta cierre | mecha | congelados "
             "| huecos propios | caídas | episodios | report |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for f in found:
        m = f["per_year_median"]
        lines.append(f"| {f['feed']} | {f['K']} | {f['stable_from']} | {f['marked_per_year']:g} | "
                     f"{m['cierre y vuelta']:g} | {m['mecha y vuelta']:g} | {m['congelado']:g} | "
                     f"{m['hueco']:g} | {m['caída del proveedor']:g} | {len(f['episodes'])} | "
                     f"`feedQuality/{f['feed']}/` |")
    return "\n".join(lines + ["", END])


def write_index(block: str) -> None:
    """Put the block into AlgoData/INDEX.md, replacing the previous one."""
    path = DATA / "INDEX.md"
    text = path.read_text(encoding="utf-8")
    if BEGIN in text:
        text = text[:text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    else:
        text = text.rstrip("\n") + "\n\n" + block + "\n"
    path.write_text(text, encoding="utf-8")


def main() -> None:
    """Scan every feed (or those named) and refresh the index."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--feed", action="append", default=[], help="one feed; all when omitted")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--set", action="extend", nargs="+", default=[], help="section.key=value")
    a = ap.parse_args()
    CFG.update(inputs.config(a.set))
    progress(2, "calendario")
    dukas = {f: (inputs.bars(f)["at"], session.without_hours(inputs.week_mask(CFG, f),
                                                              CFG["rollover_hours"]))
             for f in inputs.calendar_feeds()}
    RUNS.append(calendar.silences(dukas, CFG))
    del dukas
    RUNS[0].to_parquet(feed_quality_dir() / "calendar.parquet")
    names = a.feed or inputs.feeds()
    found = {}
    for n, (name, got) in enumerate(fanout.run(one, {f: 1 for f in names}, a.workers)):
        found[name] = got
        progress(5 + 95 * (n + 1) // len(names), name)
        print(f"{name:26s} K={got['K']}  estable {got['stable_from']}  "
              f"{got['marked_per_year']:g} marcadas/año  huecos {got['residual_gaps_per_year']:g}/año  "
              f"{len(got['episodes'])} episodios")
    every = [json.loads((feed_quality_dir(f) / "summary.json").read_text())
             for f in inputs.feeds() if (feed_quality_dir(f) / "summary.json").exists()]
    write_index(index_rows(every))
    print(f"-> {feed_quality_dir()}  ·  {np.sum([len(f['episodes']) for f in every])} "
          f"meses de episodio en {len(every)} feeds; INDEX.md al día")


if __name__ == "__main__":
    main()
