#!/usr/bin/env python3
"""Generate docs/DEPENDENCIES.md from the imports actually present in the project's Python files."""

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "DEPENDENCIES.md"
SKIP_DIRS = {".venv", "__pycache__", ".git", "scratch", "sqx-lab", "snapshots", "archive"}
STDLIB = sys.stdlib_module_names


def py_files() -> list[Path]:
    """Every project Python file worth mapping.

    Returns:
        Absolute paths, sorted, excluding vendored, scratch and cache directories.
    """
    return sorted(p for p in ROOT.rglob("*.py")
                  if not SKIP_DIRS & set(p.relative_to(ROOT).parts))


def internal_names(files: list[Path]) -> set[str]:
    """Top-level names an import can refer to inside this project.

    Args:
        files: Project Python files.

    Returns:
        Package directory names plus every module stem, e.g. {"core", "plots"}.
    """
    names = {p.stem for p in files}
    names |= {p.relative_to(ROOT).parts[0] for p in files if len(p.relative_to(ROOT).parts) > 1}
    return names


def imports_of(path: Path) -> set[str]:
    """Top-level module names imported by one file.

    Args:
        path: A Python source file.

    Returns:
        First segment of every import, e.g. "numpy" for "import numpy.linalg".
        Relative imports are reported as the bare name they import.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            found |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom) and node.module:
            found.add(node.module.split(".")[0])
    return found


def summary(path: Path) -> str:
    """The module docstring's first line, or a marker when there is none.

    Args:
        path: A Python source file.

    Returns:
        One line of prose describing the module.
    """
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    return doc.splitlines()[0] if doc else "— no module docstring —"


def render(files: list[Path]) -> str:
    """Build the whole DEPENDENCIES.md text.

    Args:
        files: Project Python files.

    Returns:
        Markdown. Carries no timestamp, so regenerating an unchanged tree is a no-op.
    """
    known = internal_names(files)
    rows, reverse, external = [], {}, {}
    for f in files:
        # as_posix, not str: the map is committed, and a Windows run must not rewrite
        # every path in it with backslashes.
        rel = f.relative_to(ROOT).as_posix()
        used = imports_of(f)
        inside = sorted(n for n in used if n in known)
        outside = sorted(n for n in used if n not in known and n not in STDLIB)
        rows.append((rel, summary(f), inside, outside, len(f.read_text(encoding="utf-8").splitlines())))
        for name in inside:
            reverse.setdefault(name, []).append(rel)
        for name in outside:
            external.setdefault(name, []).append(rel)

    out = ["# DEPENDENCIES — generated",
           "",
           "Generated by `python3 tools/depmap.py`. **Never edit by hand.**",
           "Regenerate after touching code; `tools/checks.py` fails when this file is stale.",
           "",
           "## Modules",
           "",
           "| file | lines | what it is | imports from project | external |",
           "|---|---|---|---|---|"]
    for rel, doc, inside, outside, n in rows:
        out.append(f"| `{rel}` | {n} | {doc} | {', '.join(inside) or '—'} | "
                   f"{', '.join(outside) or '—'} |")

    out += ["", "## Who depends on what", "",
            "| project module | imported by |", "|---|---|"]
    for name in sorted(reverse):
        out.append(f"| `{name}` | {', '.join(f'`{p}`' for p in sorted(reverse[name]))} |")

    out += ["", "## External libraries", "",
            "| library | used in |", "|---|---|"]
    for name in sorted(external):
        out.append(f"| `{name}` | {', '.join(f'`{p}`' for p in sorted(external[name]))} |")
    return "\n".join(out) + "\n"


def main() -> None:
    """Write docs/DEPENDENCIES.md and report how many files were mapped."""
    files = py_files()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render(files), encoding="utf-8")
    print(f"mapped {len(files)} files -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
