#!/usr/bin/env python3
"""Regenerate each knowhow/<domain>/INDEX.md from its cards' q: lines, and check the cards."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KNOWHOW = ROOT / "knowhow"
HEADER_LINES = 12
MAX_BYTES = 6 * 1024
REFERENCE = re.compile(r"knowhow/[\w./-]*[\w/]")
SCANNED = {".md", ".py", ".yaml", ".sh"}
SKIPPED = {"audit", "scratch", ".git", "sqx-lab"}


def cards() -> list[Path]:
    """Every fact card: a .md inside a domain folder, index excluded."""
    return sorted(p for p in KNOWHOW.glob("*/*.md") if p.name != "INDEX.md")


def front(card: Path) -> dict[str, str]:
    """The q:, tag:, date: and see: fields of a card's frontmatter.

    Args:
        card: Path of a card.

    Returns:
        Field name to raw text. tag, date and see share one line, so they are split on
        their own keywords rather than on newlines.
    """
    head = card.read_text(encoding="utf-8").split("---")[1]
    return {m.group(1): m.group(2).strip()
            for m in re.finditer(r"\b(q|tag|date|see):\s*(.*?)(?=\s+\b(?:tag|date|see):|\n|$)", head)}


def render(domain: Path) -> str:
    """One domain's INDEX.md: a line per card, slug and the question it answers."""
    lines = [f"# knowhow/{domain.name} — generated by tools/knowhowmap.py, do not edit", ""]
    lines += [f"- `{c.stem}` — {front(c).get('q', '')}" for c in cards() if c.parent == domain]
    return "\n".join(lines) + "\n"


def domains() -> list[Path]:
    """Every domain folder under knowhow/."""
    return sorted(p for p in KNOWHOW.iterdir() if p.is_dir())


def bad_cards(files: list[Path]) -> list[str]:
    """Cards without q:/tag:, with a header over 12 lines, a dangling see:, or over 6 KB.

    Args:
        files: Unused; the signature every check in checks.py shares.

    Returns:
        One message per offending card. The 3 KB target in knowhow/INDEX.md is guidance;
        only 6 KB fails, the size at which a card has become two facts or a diary.
    """
    out = [f"knowhow/{p.name}: a loose file at the root — the old topic files are gone, write a card"
           for p in KNOWHOW.glob("*.md") if p.name != "INDEX.md"]
    known = {c.stem for c in cards()} | {f"{c.parent.name}/{c.stem}" for c in cards()}
    for c in cards():
        rel, text = c.relative_to(ROOT), c.read_text(encoding="utf-8")
        fields = front(c)
        if not fields.get("q") or not fields.get("tag"):
            out.append(f"{rel}: no q: or tag: in the frontmatter")
        if sum(1 for ln in text.split("## Evidence")[0].splitlines() if ln.strip()) > HEADER_LINES:
            out.append(f"{rel}: header above ## Evidence is over {HEADER_LINES} lines")
        for ref in re.split(r"[,\s]+", fields.get("see", "")):
            ref = ref.strip("`[]").removeprefix("knowhow/").removesuffix(".md").rstrip("/")
            if ref and ref != "-" and ref not in known and not (KNOWHOW / ref).is_dir():
                out.append(f"{rel}: see: {ref} is not a card")
        size = len(text.encode("utf-8"))
        if size > MAX_BYTES:
            out.append(f"{rel}: {size:,} bytes, split it (max {MAX_BYTES:,})")
    return out


def broken_links(files: list[Path]) -> list[str]:
    """References to knowhow/... anywhere in the repo that point at nothing.

    Args:
        files: Unused; the signature every check in checks.py shares.

    Returns:
        One message per dangling reference, with the file and line that holds it.
    """
    out = []
    for f in ROOT.rglob("*"):
        if f.suffix not in SCANNED or SKIPPED & set(f.relative_to(ROOT).parts):
            continue
        for i, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            for ref in REFERENCE.findall(line):
                if not (ROOT / ref).exists():
                    out.append(f"{f.relative_to(ROOT)}:{i}: {ref} does not exist")
    return out


def stale_indexes(files: list[Path]) -> list[str]:
    """Domain INDEX.md files that no longer match their cards.

    Args:
        files: Unused; the signature every check in checks.py shares.

    Returns:
        One message per missing or stale index.
    """
    return [f"knowhow/{d.name}/INDEX.md: stale, run tools/knowhowmap.py" for d in domains()
            if not (d / "INDEX.md").exists()
            or (d / "INDEX.md").read_text(encoding="utf-8") != render(d)]


def main() -> None:
    """Rewrite every domain index and print how many cards each holds."""
    for d in domains():
        (d / "INDEX.md").write_text(render(d), encoding="utf-8")
    print(", ".join(f"{d.name} {sum(c.parent == d for c in cards())}" for d in domains()))


if __name__ == "__main__":
    main()
